# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Attribute-Final
version:      1.3
version_from: Final.pm
installdirs:  site
requires:
    Attribute::Handlers:           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
